In [1]:
#Importing analysis libraries

import pandas as pd
import numpy as np

import matplotlib as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.impute import SimpleImputer

from sklearn.metrics import accuracy_score,classification_report
from sklearn.metrics import mean_squared_error,r2_score

In [2]:
#Loading dataset
dataset=pd.read_csv(r"C:\Users\Rahat Mahfuz\Data_Science\ML_Bootcamp\Bootcamp_Assignment\Assignment_2\synthetic_noisy_dataset_40k_15col.csv")

In [3]:
#Showing the dataset
dataset

,age,income,experience_years,education_years,hours_worked_per_week,satisfaction_score,department,city,performance_rating,projects_completed,training_hours,remote_work_ratio,tenure_years,overtime_hours,target_salary
0,58.0,69549.87,39.0,12.0,39.3,6.14,Engineering,Sylhet,2.0,5.0,35.9,0.497,39.0,2.8,68384.37
1,52.0,60693.22,32.0,16.0,29.5,7.23,Marketing,Dhaka,5.0,5.0,6.3,0.671,32.0,2.2,65594.91
2,43.0,45906.57,25.0,19.0,58.1,7.71,HR,Rajshahi,4.0,1.0,26.9,0.187,25.0,0.5,49246.79
3,58.0,65469.20,NaN,10.0,38.9,7.45,Engineering,Chittagong,4.0,3.0,13.3,0.255,39.0,13.7,72753.03
4,45.0,60345.96,24.0,17.0,34.6,4.05,Finance,Sylhet,4.0,8.0,7.1,0.612,22.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40195,29.0,50688.43,9.0,19.0,NaN,7.12,Marketing,Rajshahi,4.0,7.0,70.5,0.772,8.0,NaN,38827.35
40196,61.0,76448.18,39.0,9.0,36.9,4.78,Engineering,Chittagong,2.0,6.0,14.2,0.728,39.0,0.0,64465.61
40197,54.0,59630.08,32.0,16.0,35.6,7.31,Marketing,Sylhet,4.0,4.0,NaN,0.628,31.0,6.8,59792.21
40198,26.0,50118.92,NaN,11.0,44.8,7.08,Engineering,Khulna,3.0,2.0,9.3,0.376,NaN,0.0,33740.75
40199,30.0,35275.20,8.0,11.0,52.4,6.01,Engineering,Khulna,2.0,8.0,9.1,0.455,8.0,9.4,26756.51

In [4]:
#dataset info
dataset.describe()

,age,income,experience_years,education_years,hours_worked_per_week,satisfaction_score,performance_rating,projects_completed,training_hours,remote_work_ratio,tenure_years,overtime_hours,target_salary
count,38999.000000,38973.000000,38976.000000,38993.000000,39026.000000,38976.000000,38999.000000,38968.000000,38924.000000,38990.000000,39009.000000,39023.000000,39014.000000
mean,42.987846,56561.266768,23.548389,13.519068,39.901409,6.979681,3.449678,5.007545,19.893287,0.499254,22.588633,5.219560,54137.682185
std,16.303781,24437.293547,14.996272,3.442483,8.575831,1.468802,1.024358,2.239215,19.985953,0.223667,14.910648,3.666825,20009.650690
min,-69.000000,10977.770000,0.000000,8.000000,0.000000,0.420000,1.000000,0.000000,0.000000,0.003000,0.000000,0.000000,1511.010000
25%,30.000000,44058.210000,10.000000,11.000000,34.600000,5.990000,3.000000,3.000000,5.800000,0.327000,9.000000,2.300000,40367.480000
50%,43.000000,54984.590000,23.000000,14.000000,40.100000,6.990000,3.000000,5.000000,13.700000,0.499000,22.000000,5.000000,53310.215000
75%,57.000000,66053.220000,37.000000,17.000000,45.500000,8.000000,4.000000,6.000000,27.500000,0.673000,36.000000,7.700000,66436.262500
max,69.000000,552732.460000,51.000000,19.000000,71.200000,10.000000,5.000000,18.000000,232.200000,0.998000,51.000000,21.400000,332112.840000

In [5]:
#Data Cleaning

#missing values
dataset.isnull().sum()

age                      1201
income                   1227
experience_years         1224
education_years          1207
hours_worked_per_week    1174
satisfaction_score       1224
department                  0
city                        0
performance_rating       1201
projects_completed       1232
training_hours           1276
remote_work_ratio        1210
tenure_years             1191
overtime_hours           1177
target_salary            1186
dtype: int64

In [6]:
#numerical columns
numerical_columns=dataset.select_dtypes(include=np.number).columns

imputer=SimpleImputer(strategy='median')
dataset[numerical_columns]=imputer.fit_transform(dataset[numerical_columns])

In [7]:
#categorical columns
categorical_columns=dataset.select_dtypes(include='object').columns

imputer_category=SimpleImputer(strategy='most_frequent')
dataset[categorical_columns]=imputer_category.fit_transform(dataset[categorical_columns])

C:\Users\Rahat Mahfuz\AppData\Local\Temp\ipykernel_11724\3132578331.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns=dataset.select_dtypes(include='object').columns

In [8]:
#removing duplicates
dataset.drop_duplicates(inplace=True)
dataset

,age,income,experience_years,education_years,hours_worked_per_week,satisfaction_score,department,city,performance_rating,projects_completed,training_hours,remote_work_ratio,tenure_years,overtime_hours,target_salary
0,58.0,69549.87,39.0,12.0,39.3,6.14,Engineering,Sylhet,2.0,5.0,35.9,0.497,39.0,2.8,68384.370
1,52.0,60693.22,32.0,16.0,29.5,7.23,Marketing,Dhaka,5.0,5.0,6.3,0.671,32.0,2.2,65594.910
2,43.0,45906.57,25.0,19.0,58.1,7.71,HR,Rajshahi,4.0,1.0,26.9,0.187,25.0,0.5,49246.790
3,58.0,65469.20,23.0,10.0,38.9,7.45,Engineering,Chittagong,4.0,3.0,13.3,0.255,39.0,13.7,72753.030
4,45.0,60345.96,24.0,17.0,34.6,4.05,Finance,Sylhet,4.0,8.0,7.1,0.612,22.0,0.0,53310.215
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40195,29.0,50688.43,9.0,19.0,40.1,7.12,Marketing,Rajshahi,4.0,7.0,70.5,0.772,8.0,5.0,38827.350
40196,61.0,76448.18,39.0,9.0,36.9,4.78,Engineering,Chittagong,2.0,6.0,14.2,0.728,39.0,0.0,64465.610
40197,54.0,59630.08,32.0,16.0,35.6,7.31,Marketing,Sylhet,4.0,4.0,13.7,0.628,31.0,6.8,59792.210
40198,26.0,50118.92,23.0,11.0,44.8,7.08,Engineering,Khulna,3.0,2.0,9.3,0.376,22.0,0.0,33740.750
40199,30.0,35275.20,8.0,11.0,52.4,6.01,Engineering,Khulna,2.0,8.0,9.1,0.455,8.0,9.4,26756.510

In [9]:
#handling invalid categories
for columns in categorical_columns:
    dataset[columns].str.strip().str.lower()

In [10]:
#Outlier detection
for columns in numerical_columns:
    Q1=dataset[columns].quantile(1/4)
    Q3=dataset[columns].quantile(3/4)
    IQR=Q3-Q1
    
    lower_limit=Q1-1.5*IQR
    upper_limit=Q3+1.5*IQR
    
    dataset=dataset[(dataset[columns]>=lower_limit)&(dataset[columns]<=upper_limit)]
    
    dataset

In [11]:
#identifying problem type
dataset.columns
target_salary='target_salary'
dataset[target_salary].dtype

#Here target salary is a numerical value.So it will be an Regression Model.

dtype('float64')

In [12]:
#Encoding categorical values
encoding=LabelEncoder()

for columns in categorical_columns:
    dataset[columns]=encoding.fit_transform(dataset[columns])

In [13]:
#splitting features
x=dataset.drop(target_salary,axis=1)
y=dataset[target_salary]

In [14]:
#train-test and split
x_trained,x_test,y_train,y_test=train_test_split(
    x,y,
    test_size=0.2,
    random_state=42
)

In [15]:
#feature scaling
number_columns=x_trained.select_dtypes(include="number").columns

scaling=StandardScaler()

x_trained[number_columns]=scaling.fit_transform(x_trained[number_columns])
x_test[number_columns]=scaling.transform(x_test[number_columns])

In [16]:
#model selection
#the type of data is float64.So,it is a numerical value.It will be a regression model
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

In [17]:
#training the model
linear_regression=LinearRegression()
decision_tree=DecisionTreeRegressor()
random_forest=RandomForestRegressor()

linear_regression.fit(x_trained,y_train)
decision_tree.fit(x_trained,y_train)
random_forest.fit(x_trained,y_train)

RandomForestRegressor()

In [18]:

#prediction
prediction_1=linear_regression.predict(x_test)
prediction_2=decision_tree.predict(x_test)
prediction_3=random_forest.predict(x_test)

In [ ]:
#evaluation
#choosing the best model with the highest percentage of accuracy
print("Linear Regression")
print(r2_score(y_test,prediction_1))

print("Decision Tree")
print(r2_score(y_test,prediction_2))

print("Random Forest")
print(r2_score(y_test,prediction_3))

Linear Regression
0.8640067643725952
Decision Tree
0.7273652226520909
Random Forest
0.8669353412410664

In [ ]:
#The highest score is fro the Random Forest Model.Which is 86.69% of accuracy.So,between these 3 models Random Forest is the best model.